### ISSUE TITLE
PR for Bokeh?

### ISSUE THREAD

**Issue by bryevdv** [akloster/nb-bokeh-animations#1]
@akloster I actually intended to add support for triggering re-renders in the notebook so that streaming/animation could be accomplished without the server (at least, in the notebook). Would you be interested in contributing this work to Bokeh directly?

**Comment by akloster** [comment]
I would be interested to contribute something like this. The problem I see is that in my current "vision" of this it's still necessary to manually optimize the updating. To make it more general, it might be necessary to separate between data source updates and triggering render events.

I think in Bokeh the general idea was to handle this stuff automatically inside the "session" manager, but I haven't gotten into that yet.

Also the handling of the widgets would have to be optimized. In the examples I am using widgets which don't contain the graphics itself but open the communication channel, so to speak. Maybe the plots should be moved inside the widget (which is possible), but then they would not behave like normal output does...

There's a lot to think about...

**Comment by bryevdv** [comment]
As a first start, just being able to have BokehJS data sources get updated whenever a python data source is updated would go a very long way. If you had that, you could use IPython interactors directly, and just updated the python data sources to update the plots. Or just update the data sources in a loop, or whatever. That's a small piece of work that goes a long way, so my suggestion would be to look at just that, first, and we could discuss a plan for Bokeh widgets later.

**Comment by akloster** [comment]
Hm, it should be possible to have some kind of event listeners on the python side, telling the python-side widget to trigger the update.

Maybe it would be better to track if the data sources changed since they were last updated in the browser. Then you wouldn't have to update on every single change, and just call an update() function somewhere.

I'll see what I can come up with.

**Comment by bryevdv** [comment]
BokehJS actually calls `request_render` on JS data source updates, which is throttled, so I think the simplest path is also the best path. I would even say start with an explicit function: `bokeh.notebook.update_datasource` or something that updates the JS data source from the python one.  Can worry about triggering that function automatically off updates to the python data source as a second step.

**Comment by akloster** [comment]
I'm still working on this. I have learned some more about the issues of updating plots in the notebook. For example I am experimenting with different ways to throttle streaming in case of too many data points, how to deal with loops and removed widgets/plots.

**Comment by bryevdv** [comment]
ping @mattpap may have some comments as well. If you do want to make a PR sooner rather than later, we would be happy to test it out and give feedback.

**Comment by akloster** [comment]
Can you give me suggestions how to include the widget code into bokeh? Both the javascript and python code.

I also have some problems setting up bokehjs for development. I can build it, but short of building and reinstalling bokeh completely, I can't refresh the code, which is awkward.

**Comment by bryevdv** [comment]
@akloster we have proceeded with some basic functionality (just updating a data source, no animation widget yet). I would like to work up some of your notebook examples into the bokek examples directory. Is this acceptable to you?

**Comment by akloster** [comment]
Yes, of course. I have also found a way to use selections and selection callbacks.

The display_javascript way of updating data sources may prove impractical for too many updates, as the script tags keep accumulating. When reloading the notebook, they are all executed at once. This can be prevented by calling clear_output, but that also removes all other output of the current cell.

**Comment by bryevdv** [comment]
@akloster Oh that is a good thing to consider, I will run it by some folks. We definitely want to expand on this for 0.7.1 but this seems important and desirable enough that we should get something in the hands of folks now. Thanks again!
